### ISSUE TITLE
Exposing the documentation with express-static

### ISSUE THREAD

**Issue by firla** [jakemmarsh/expressed-boilerplate#2]
Hi, I am not sure how to serve the documentation. I tried to integrate the /docs directory with express.static in "server.js" but it doesn't work:

```
server.use('/doc', express.static(__dirname + '/docs'));
```

http://localhost:3000/doc/index.html returns always a 404.
Thx Firla

**Comment by jakemmarsh** [comment]
Hm, can you provide the entire `server.js` file after you've added that line? Also, have you ensured that the docs have been generated and the `/docs` directory exists? I just added the exact same line to my local copy and it seemed to work just fine at the URL you gave.

**Comment by firla** [comment]
Thanks for your fast answer. Yes, I have created the /docs and a gist with all informations:

https://gist.github.com/anonymous/51f5594d4b73ff69bf92

**Comment by jakemmarsh** [comment]
Do the endpoints at `/api/v1` still work correctly? I'm still failing to reproduce and I don't see any glaring problems with your code.

**Comment by hour1** [comment]
Yes, they work.

Ok, I will check the implementation in detail. I only wanted to make sure than I don't miss a obvious setting. If you want, please close the ticket.

Thank you!

**Comment by firla** [comment]
Yes, they work.

Ok, I will check the implementation in detail. I only wanted to make sure than I don't miss a obvious setting.

Thank you!
